admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Dashboard:index }
admin_AfficherUser:
    path:     /AfficherUser
    defaults: { _controller: AdminBundle:Dashboard:AfficherUser}
admin_ ajouteractualite:
    path:     /ajouteractualite
    defaults: { _controller: AdminBundle:Dashboard:ajouteractualite}
