ecommerce_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Default:index }
Afficherpannier:
    path:     /Afficherpannier/{id}
    defaults: { _controller: EcommerceBundle:Paiement:Afficherpannier }
panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Paiement:panier }
ajoute:
    path:     /ajout/{id}
    defaults: { _controller: EcommerceBundle:Paiement:ajouter }
supprimer:
    path:    /supprimer/{id}
    defaults: { _controller: EcommerceBundle:Paiement:supprimer }
menu:
    path:    /menu
    defaults: { _controller: EcommerceBundle:Paiement:menu }
commander_produit:
    path:    /putinsession/{id}
    defaults: { _controller: EcommerceBundle:LigneDeCommande:PutInSession }
ajout_ligne_commande:
    path:     /ajoutbd
    defaults: { _controller: EcommerceBundle:LigneDeCommande:AjoutLigneDeCommande }
afficher_commande:
    path:     /afficherCommande
    defaults: { _controller: EcommerceBundle:LigneDeCommande:afficherCommande }
ligne_commande_aff:
    path:     /afflc/{id}
    defaults: { _controller: EcommerceBundle:LigneDeCommande:AfficherLigneDeCommande }
ligne_commande_modifier:
    path:     /modifierlc/{id}
    defaults: { _controller: EcommerceBundle:LigneDeCommande:ModifierLigneDeCommande }
ligne_commande_supprimer:
    path:     /supprimerlc/{id}
    defaults: { _controller: EcommerceBundle:LigneDeCommande:SupprimerLigneDeCommande }
