user_page_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_inscription:
    path:     /register
    defaults: { _controller: UserBundle:Default:inscription}
list_reparations:
    path:     /list
    defaults: { _controller: UserBundle:Default:Reparateurs}
Location:
    path:     /Location
    defaults: { _controller: UserBundle:Default:location}
Affichervelo:
    path:     /Affichervelo/{id}
    defaults: { _controller: UserBundle:Default:Affichervelo}
RoadBike:
    path:     /RoadBike
    defaults: { _controller: UserBundle:Velo:RoadBike}
KidsBikes:
    path:     /KidsBikes
    defaults: { _controller: UserBundle:Velo:KidsBikes}
MountainBikes  :
    path:     /MountainBikes
    defaults: { _controller: UserBundle:Velo:MountainBikes}
SportsBike:
    path:     /SportsBike
    defaults: { _controller: UserBundle:Velo:SportsBike}
CyclocrossBike:
    path:     /CyclocrossBike
    defaults: { _controller: UserBundle:Velo:CyclocrossBike}
prixasc_produits:
    path:     /prixasc-produits
    defaults: { _controller: UserBundle:Velo:prixasc }

prixdesc_produits:
    path:     /prixdescproduits
    defaults: { _controller: UserBundle:Velo:prixdescendant }


